### ISSUE TITLE
How is the frontend container getting the `API_URL`?

### ISSUE THREAD

**Issue by naman-memechat** [knaopel/docker-frontend-backend-db#2]
I looked into the code and can't find any .env file passed or environment variable being created for the variable API_URL. Please tell me about it.

**Comment by gotursix** [comment]
It is located in the environment file located at https://github.com/knaopel/docker-frontend-backend-db/tree/master/frontend/.env.development

**Comment by hazradwip** [comment]
If I want to make an image of this and want to deploy it on cloud how could I pass the API_URL..

**Comment by knaopel** [comment]
@naman-memechat as @gotursix mentioned, the file [/frontend/.env.development](https://github.com/knaopel/docker-frontend-backend-db/tree/master/frontend/.env.development) contains a definition for REACT_APP_API_URL.
Then in [/frontend/src/components/home.jsx](https://github.com/knaopel/docker-frontend-backend-db/tree/master/frontend/src/components/home.jsx) on line 16 that environment variable is put into the local variable API_URL.
